{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "solana-kit-android",
    "version": "408a2bb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-408a2bb.aar",
          "url": "solana-kit-android-408a2bb.aar",
          "size": 490791,
          "sha512": "a83852fafc3702df6d02fc66a26e47974b95bd0609b51141729a699ad06f3f77a086dc7f00df76f79af41c2f64f8ae7d4d443522d4ee49bb838fd11ec902e6b0",
          "sha256": "79f892b6d034c3b7b7602fd59a6cb1a8639af16beab9de53917f7efa758f8d8d",
          "sha1": "85d3b8edd5413cbe7ad24059d6fe458a04fcc3a0",
          "md5": "eccc73015f61fe8675b937a49ed4e84c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.sol4k",
          "module": "sol4k",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "SolanaKT",
          "version": {
            "requires": "864ec19"
          }
        },
        {
          "group": "com.github.metaplex-foundation",
          "module": "metaplex-android",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "com.github.metaplex-foundation",
              "module": "SolanaKT"
            },
            {
              "group": "com.github.metaplex-foundation.kborsh",
              "module": "kborsh-jvm"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-408a2bb.aar",
          "url": "solana-kit-android-408a2bb.aar",
          "size": 490791,
          "sha512": "a83852fafc3702df6d02fc66a26e47974b95bd0609b51141729a699ad06f3f77a086dc7f00df76f79af41c2f64f8ae7d4d443522d4ee49bb838fd11ec902e6b0",
          "sha256": "79f892b6d034c3b7b7602fd59a6cb1a8639af16beab9de53917f7efa758f8d8d",
          "sha1": "85d3b8edd5413cbe7ad24059d6fe458a04fcc3a0",
          "md5": "eccc73015f61fe8675b937a49ed4e84c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "solana-kit-android-408a2bb-sources.jar",
          "url": "solana-kit-android-408a2bb-sources.jar",
          "size": 125987,
          "sha512": "3a77971b1b565f83994c518dee0aa358133124e6b02858bcdb7cc5de46c5c62f1a7f67bcbb3210f5e9cd744294c29a768a8b1f6a2f776aec9c8307fa5fda73d6",
          "sha256": "1df0833587d55c1b2af30251ebb4a28283345f1ac42852e14f44a826fe1f6ae3",
          "sha1": "e5d38fb7320fb731dc4678622d2872cf684490ad",
          "md5": "42810b539365f7fdc833bb94a8e6302c"
        }
      ]
    }
  ]
}
