{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "solana-kit-android",
    "version": "2c36bd5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-2c36bd5.aar",
          "url": "solana-kit-android-2c36bd5.aar",
          "size": 489584,
          "sha512": "a1f6ce8e3a3a8879a2e2609a0cd7de6067ce3272c7a1c24d1ea36eac9d29bd43214253d963e607c4c3bef5c22082877f96bf447df135762287b1393293ad3127",
          "sha256": "93af9a962f33d3af7007854aaff93c5db7b3a9efbc051fb0a22280d3468bde86",
          "sha1": "b6bc3f78bd90deab901bf03f0ec202633fa02587",
          "md5": "89fded4377c00c194fba8b8f26c4c029"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.sol4k",
          "module": "sol4k",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "SolanaKT",
          "version": {
            "requires": "5d5a0cb"
          }
        },
        {
          "group": "com.github.metaplex-foundation",
          "module": "metaplex-android",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "com.github.metaplex-foundation",
              "module": "SolanaKT"
            },
            {
              "group": "com.github.metaplex-foundation.kborsh",
              "module": "kborsh-jvm"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-2c36bd5.aar",
          "url": "solana-kit-android-2c36bd5.aar",
          "size": 489584,
          "sha512": "a1f6ce8e3a3a8879a2e2609a0cd7de6067ce3272c7a1c24d1ea36eac9d29bd43214253d963e607c4c3bef5c22082877f96bf447df135762287b1393293ad3127",
          "sha256": "93af9a962f33d3af7007854aaff93c5db7b3a9efbc051fb0a22280d3468bde86",
          "sha1": "b6bc3f78bd90deab901bf03f0ec202633fa02587",
          "md5": "89fded4377c00c194fba8b8f26c4c029"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "solana-kit-android-2c36bd5-sources.jar",
          "url": "solana-kit-android-2c36bd5-sources.jar",
          "size": 125251,
          "sha512": "ed37dfc2c6d4d33dc3e6e563561f3e0f7c96817358816dc3cd9b250205b43d00da0a7753217c26d279141ea9e8f30ac75ea41641e737fea8564b986caa24dd72",
          "sha256": "4b233d361d3a3eee35a69654c6dc4ba52677ec11960251d6292a5fef3eddc572",
          "sha1": "a694086909ae58b3075c924f605e4a4bdf968786",
          "md5": "05af6c6a7b72ae3f77d84e26f0cb5f45"
        }
      ]
    }
  ]
}
