{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "solana-kit-android",
    "version": "f65d425",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-f65d425.aar",
          "url": "solana-kit-android-f65d425.aar",
          "size": 408400,
          "sha512": "f3a68e6dadf3818ddc4aa152f3e0e595ce46d726fc36c4fe82a5f082133a6561d868cbc1fb0eb76a198de3bf1c17367ab8b2cc7cc7be7378ccfd068f9443890f",
          "sha256": "6f50710570487e948f6f844b9dc07ca5ae6275837ff106c9d041cde869505436",
          "sha1": "01d2c736b1628b3bf395360b3d3bbc0dd1de9f5d",
          "md5": "e706676cfcc4d63987baf997633e38e1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.sol4k",
          "module": "sol4k",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "SolanaKT",
          "version": {
            "requires": "b35be52"
          }
        },
        {
          "group": "com.github.metaplex-foundation",
          "module": "metaplex-android",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "com.github.metaplex-foundation",
              "module": "SolanaKT"
            },
            {
              "group": "com.github.metaplex-foundation.kborsh",
              "module": "kborsh-jvm"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-f65d425.aar",
          "url": "solana-kit-android-f65d425.aar",
          "size": 408400,
          "sha512": "f3a68e6dadf3818ddc4aa152f3e0e595ce46d726fc36c4fe82a5f082133a6561d868cbc1fb0eb76a198de3bf1c17367ab8b2cc7cc7be7378ccfd068f9443890f",
          "sha256": "6f50710570487e948f6f844b9dc07ca5ae6275837ff106c9d041cde869505436",
          "sha1": "01d2c736b1628b3bf395360b3d3bbc0dd1de9f5d",
          "md5": "e706676cfcc4d63987baf997633e38e1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "solana-kit-android-f65d425-sources.jar",
          "url": "solana-kit-android-f65d425-sources.jar",
          "size": 109678,
          "sha512": "a332b0b83dc292a316041b0222f29d72361c51d40a9792e213ddcefc5ccc8efa503ac0cf91a03cac9cbd32c4bb07f844c3c4477e2a0e89f5d951386b0c3e5652",
          "sha256": "0fc0c6a72b7b9b129a7ea0747c71fb8d847840d17c4028d984cc09c828635bab",
          "sha1": "cd808e1cd7652deb9bd8b6368a97a44e17612c89",
          "md5": "033466a46ee59332d91e71c4516f952f"
        }
      ]
    }
  ]
}
