plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
def localProperties = new Properties()
localProperties.load(new FileInputStream(rootProject.file("local.properties")))

android {
    compileSdk 34
    android.buildFeatures.buildConfig true
    defaultConfig {
        applicationId 'io.horizontalsystems.solanakit'
        minSdk 27
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        applicationIdSuffix 'sample'
        buildConfigField "String", "WORDS", "${localProperties['words']}"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'io.horizontalsystems.solanakit.sample'

    def bcprovVersionsToRedirect = [
            'bcprov-jdk15on:1.65',
            'bcprov-jdk15on:1.65.01',
            'bcprov-jdk15on:1.66',
            'bcprov-jdk15on:1.70',
            'bcprov-jdk15to18:1.65',
            'bcprov-jdk15to18:1.65.01',
            'bcprov-jdk15to18:1.68',
            'bcprov-jdk15to18:1.69'
    ]
    configurations.all { c ->
        c.resolutionStrategy.dependencySubstitution {
            bcprovVersionsToRedirect.each { moduleId ->
                def (name, version) = moduleId.split(':')
                substitute module("org.bouncycastle:$name:$version") using module("org.bouncycastle:bcprov-jdk15to18:1.80")
            }
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.6.0'
    implementation 'androidx.navigation:navigation-ui-ktx:2.6.0'
    implementation(libs.hd.wallet.kit.android) {
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk15to18'
    }

    implementation project(':solanakit')

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

}
