{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "solana-kit-android",
    "version": "daa46e5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-daa46e5.aar",
          "url": "solana-kit-android-daa46e5.aar",
          "size": 420109,
          "sha512": "9882197d57b9d33cdb6282626714131df28941e12881575a36c00d8a431ea887e2f1abeccbb8ebdb18b5a0a4f2710d87ab3e93279840d4dbdc6543bb08c994fc",
          "sha256": "867482386a6ce6b0f25a270dc8a499c77ed5e63e99f5b7a7a447aca880600da8",
          "sha1": "ac0fad66f42140b587db13cf98a87e64e9337fd1",
          "md5": "8cd8e607e1f785653f35fe92314488d0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.sol4k",
          "module": "sol4k",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "SolanaKT",
          "version": {
            "requires": "5d5a0cb"
          }
        },
        {
          "group": "com.github.metaplex-foundation",
          "module": "metaplex-android",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "com.github.metaplex-foundation",
              "module": "SolanaKT"
            },
            {
              "group": "com.github.metaplex-foundation.kborsh",
              "module": "kborsh-jvm"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solana-kit-android-daa46e5.aar",
          "url": "solana-kit-android-daa46e5.aar",
          "size": 420109,
          "sha512": "9882197d57b9d33cdb6282626714131df28941e12881575a36c00d8a431ea887e2f1abeccbb8ebdb18b5a0a4f2710d87ab3e93279840d4dbdc6543bb08c994fc",
          "sha256": "867482386a6ce6b0f25a270dc8a499c77ed5e63e99f5b7a7a447aca880600da8",
          "sha1": "ac0fad66f42140b587db13cf98a87e64e9337fd1",
          "md5": "8cd8e607e1f785653f35fe92314488d0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "solana-kit-android-daa46e5-sources.jar",
          "url": "solana-kit-android-daa46e5-sources.jar",
          "size": 112214,
          "sha512": "6ceed3f231ff708f45eb8b53c2ca622bd8431c31e18bdc99b63a781fe4caebb81472351f8fd6874c23e5707abefdcb44840eaf3f2eacdf70df98cdd3a60297ba",
          "sha256": "c34f191bfa77a815000347c2497d6f7ecb0c11004263ded14ffea6a3eafe9fab",
          "sha1": "b889a9cee95cbf91df8f9ad448d630616ae36052",
          "md5": "a6a4a6bc1d4dc5d1772959999f59f7f0"
        }
      ]
    }
  ]
}
